name : workflow

on:
  push:
    branches:
      - main
    path-ignore:
      - 'README.md'

jobs:
  integration:
    name : Continuous Integration
    runs-on : ubuntu-latest
    steps:
      - name : Checkout Code
        user : actions/Checkout@v3

      - name : Lint Code
        run : echo "Linting repository"

      - name : Run unit tests
        run : echo "Running unit tests" 
